baseurl = "https://lucianonooijen.nl" # Hostname (and path) to the root.
title = "Luciano Nooijen" # Site title.
theme = "lucianonooijen" # Set the theme.
languageCode = "en-us"

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Luciano Nooijen" # Author's name.
    info = "Full Stack web magician and devops engineer" # Author's job title or info.
    description = "Luciano Nooijen's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "lucianonooijen" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/lucianonooijen/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/lucianonooijen/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/lucianonooijen/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
