name = "jeroenvansteijn"
license = "MIT"
licenselink = "https://github.com/jeroenvansteijn/Personal-Website/blob/master/LICENSE"
description = "Jeroen van Steijn's theme based on https://github.com/luizdepra/hugo-coder"
homepage = "https://jeroenvansteijn.nl/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.32"

[author]
  name = "Jeroen van Steijn"
  homepage = "https://jeroenvansteijn.nl"
