name = "lucianonooijen"
license = "MIT"
licenselink = "https://github.com/luizdepra/hugo-coder/blob/master/LICENSE.md"
description = "Luciano Nooijen's theme based on https://github.com/luizdepra/hugo-coder"
homepage = "https://github.com/luizdepra/hugo-coder/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.32"

[author]
  name = "Luciano Nooijen"
  homepage = "https://lucianonooijen.com"
